package com.gid.admin.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Task")
public class Task {

	private String taskId;
	private String posterId;
	public Task(String taskId, String posterId) {
		super();
		this.setTaskId(taskId);
		this.setPosterId(posterId);
	}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getTaskId() {
		return taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	 @DynamoDBAttribute
	public String getPosterId() {
		return posterId;
	}

	public void setPosterId(String posterId) {
		this.posterId = posterId;
	}
	
	
}
